[package]
name = "adventofcode-2018"
version = "0.1.0"
authors = ["Aaron McLeod <aaron.g.mcleod@gmail.com>"]

[dependencies]
read_input = { path = "./read_input/" }

[[bin]]
name = "1"
path = "1/main.rs"
